# docker-compose.yaml  (Compose V2: sem "version:")
services:
  kafka:
    image: confluentinc/cp-kafka:${CP_VERSION:-8.0.0}
    container_name: kafka
    hostname: kafka
    ports:
      - "19092:19092"   # externo (host) -> use localhost:19092
    environment:
      # KRaft (sem ZooKeeper)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # Listeners: interno (entre containers) e externo (host)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:19092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,EXTERNAL://localhost:19092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      # Single node (DEV)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"

      # ID único do cluster KRaft (gere abaixo e cole aqui)
      CLUSTER_ID: "pIclUyxNQpO-VR-mJekbVw"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: "1"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

networks:
  default:
    name: freelas_net
