apiVersion: apps/v1
kind: Deployment
metadata:
  name: matcher
  namespace: freelas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matcher
  template:
    metadata:
      labels:
        app: matcher
    spec:
      containers:
        - name: matcher
          image: freelas-matcher:dev
          imagePullPolicy: IfNotPresent
          env:
            - name: NODE_ENV
              value: production
            - name: KAFKA_BROKERS
              value: redpanda:9092
            - name: REDIS_URL
              value: redis://redis:6379
            - name: USE_REAL_KAFKA
              value: "true"
            - name: USE_REAL_REDIS
              value: "true"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 512Mi

