apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../infra
  - ../apps
  - ingress.yaml
  - hpa-api.yaml
  - hpa-matcher.yaml
images:
  - name: freelas-api
    newName: dan1993/freelas-api
    newTag: hmg
  - name: freelas-matcher
    newName: dan1993/freelas-matcher
    newTag: hmg
  - name: freelas-web
    newName: dan1993/freelas-web
    newTag: hmg
