apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freelas-redpanda
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Danylo93/freelas-monorepo.git
    targetRevision: main
    path: k8s/apps/redpanda
  destination:
    name: in-cluster
    namespace: freelas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

