apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../..
  - ../../hpa-api.yaml
  - ../../hpa-matcher.yaml
  - ingress.yaml
images:
  - name: freelas-api
    newName: freelas-api
    newTag: dev
  - name: freelas-matcher
    newName: freelas-matcher
    newTag: dev
  - name: freelas-web
    newName: freelas-web
    newTag: dev
