apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../infra      # namespace, redis, redpanda
  - ../apps       # agrega todos os apps comuns
  - ingress.yaml  # cria o Ingress para dev
# (opcional) nameSuffix: -dev, images:, configMapGenerator:, etc.
images:
  - name: freelas-api
    newName: dan1993/freelas-api
    newTag: prd
  - name: freelas-matcher
    newName: dan1993/freelas-matcher
    newTag: prd
  - name: freelas-web
    newName: dan1993/freelas-web
    newTag: prd
