apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../apps       # agrega todos os apps comuns
patches:
  - path: ingress.yaml
    target:
      kind: Ingress
# (opcional) nameSuffix: -dev, images:, configMapGenerator:, etc.
