version: "3.9"
services:
  api:
    build:
      context: .
      args:
        API_PORT: 3001
    image: freelas-api:dev
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      API_PORT: 3001
      REDIS_URL: redis://redis:6379
      USE_REAL_KAFKA: "false"
      USE_REAL_REDIS: "true"
    ports:
      - "3001:3001"
    networks:
      - freelas_net

networks:
  freelas_net:
    external: true
