name: API CI

on:
  push:
    branches: [ main, master, develop, hmg, feature/**, hotfix/**, bugfix/** ]
  pull_request:
  workflow_dispatch: {}

concurrency:
  group: api-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: api/yarn.lock
      - name: Install
        working-directory: api
        run: |
          corepack enable
          yarn --version
          yarn install --frozen-lockfile
      - name: Build
        working-directory: api
        run: yarn build
      - name: Teste
        working-directory: api
        run: yarn test --reporter=dot
