name: CI

on:
  push:
    branches: [ main, master, develop, hmg, feature/** ]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, matcher, web]   # ajuste se quiser rodar só a api
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: ${{ matrix.service }}/yarn.lock

      # evita conflito se sobrou package-lock.json
      - name: Remove npm lockfile (se existir)
        run: |
          if [ -f package-lock.json ]; then rm -f package-lock.json; fi
          if [ -f ${{ matrix.service }}/package-lock.json ]; then rm -f ${{ matrix.service }}/package-lock.json; fi

      - name: Enable Corepack + Yarn classic
        working-directory: ${{ matrix.service }}
        run: |
          corepack enable
          yarn set version classic
          echo '{"packageManager":"yarn@1.22.22"}' > .yarnrc || true

      - name: Install deps
        working-directory: ${{ matrix.service }}
        run: yarn install --frozen-lockfile

      # Se o web depende de variável pública na build
      - name: Build
        working-directory: ${{ matrix.service }}
        env:
          NEXT_PUBLIC_API_URL: http://api.dev.localtest.me
        run: yarn build

      - name: Test
        working-directory: ${{ matrix.service }}
        run: yarn test --if-present --run
