name: Release Orchestrator

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "dev|hmg|prd"
        default: dev

jobs:
  api:
    uses: ./.github/workflows/api-release.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit

  matcher:
    uses: ./.github/workflows/matcher-release.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit

  web:
    uses: ./.github/workflows/web-release.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit

